# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule EgaPubSub.Mixfile do
  use Mix.Project

  @version "0.42.0"

  def project() do
    [
      app: :ega_pub_sub,
      version: @version,
      elixir: "~> 1.6",
      build_embedded: Mix.env == :prod,
      start_permanent: Mix.env == :prod,
      description: description(),
      package: package(),
      deps: deps(),
      source_url:
        "https://github.com/Live-Circle-Inc/ega/tree/main/clients/pub_sub"
    ]
  end

  def application() do
    [extra_applications: [:logger]]
  end

  defp deps() do
    [
      # Live Circle fork of google_gax. Carries the Tesla >= 1.18.3
      # :max_body_size fix that upstream (archived) can no longer take, and drops
      # upstream's unused {:mime, "~> 1.0"} cap.
      #
      # A version requirement, not a path dep: Hex rejects path deps in published
      # packages. This mirrors what upstream did with {:google_gax, "~> 0.4"}.
      # Consequence: publish clients/gax BEFORE clients/pub_sub, and to build
      # pub_sub locally against unpublished gax changes, add
      #   {:ega_gax, path: "../gax", override: true}
      # to a top-level project rather than editing this line.
      {:ega_gax, "~> 0.5"},

      {:ex_doc, "~> 0.16", only: :dev}
    ]
  end

  defp description() do
    """
    Google Cloud Pub/Sub API client library - maintained drop-in fork of
    google_api_pub_sub (archived upstream). Provides reliable, many-to-many,
    asynchronous messaging between applications. Fixes Tesla >= 1.18.3
    compatibility via ega_gax.
    """
  end

  defp package() do
    [
      name: "ega_pub_sub",
      files: ["lib", "mix.exs", "README*", "LICENSE"],
      maintainers: ["Live Circle"],
      licenses: ["Apache-2.0"],
      links: %{
        "GitHub" =>
          "https://github.com/Live-Circle-Inc/ega/tree/main/clients/pub_sub",
        "Upstream (archived)" =>
          "https://github.com/googleapis/elixir-google-api/tree/master/clients/pub_sub",
        "Homepage" => "https://cloud.google.com/pubsub/docs"
      }
    ]
  end
end
